---
- name: Moodle Webserver
  hosts: all
  become: yes

  vars:
    php_packages:
      - php5
      - php5-curl
      - libapache2-mod-php5
      - php5-dev
      - php5-mysql
      - php5-gd
      - php5-ldap
      - php5-intl
    php_use_managed_ini: false

  roles:
    - geerlingguy.php
    - geerlingguy.apache

  tasks:
    - name: Write the php.ini file
      copy: src=templates/php.ini dest=/etc/php5/apache2/php.ini

    - name: Change the apache docroot to /var/www
      replace:
        regexp: "DocumentRoot /var/www/html"
        replace: "DocumentRoot /var/www"
        dest: /etc/apache2/sites-enabled/000-default.conf
